In [37]:
import numpy as np #引入numpy

In [38]:
a=np.array([[1,1],[2,2]]) #创建矩阵a

In [39]:
b=np.array([[1,0],[0,1]]) #创建矩阵b

In [40]:
print(a) #打印a

[[1 1]
 [2 2]]


In [41]:
print(a-b) #打印a-b

[[0 1]
 [2 1]]


In [42]:
print(a*b) #打印矩阵a*b

[[1 0]
 [0 2]]
